// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThongNhat_Hospital.Models;

namespace ThongNhat_Hospital.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20230515083851_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ThongNhat_Hospital.Models.PhieuGiaoHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("chuky")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngaygiao")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("PhieuGiaoHang");
                });
#pragma warning restore 612, 618
        }
    }
}
